DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

School_BBS/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from users import views
from posts import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^', include('posts.urls')),
    url(r'^', include('comments.urls')),
    # 将 auth 应用中的 urls 模块包含进来
    url(r'^users/', include('django.contrib.auth.urls')),
    # 别忘记在顶部引入 views 模块
    url(r'^$', views.index, name='index'),
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.conf.urls import url

from .views import post_comment,reply

app_name = 'comments'

urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', post_comment, name='post_comment'),
    url(r'^reply/(\d+)$', reply, name='reply'),
]

posts/urls.py
from django.conf.urls import url
import posts.views as views
import posts.update as update
from .views import IndexView
app_name = 'posts'

urlpatterns = [
    url(r'^index/$', IndexView.as_view(), name='index'),
    # url(r'^index/', views.posts, name='index'),
    url(r'^categories/(?P<pk>\d+)/$', views.categories, name='categories'),
    url(r'^tags/(?P<pk>\d+)/$', views.tags, name='tags'),
    url(r'^best/(?P<pk>\d+)/$', views.tags, name='best'),
    url(r'^detail/(?P<pk>\d+)/$',views.detail, name='detail'),
    url(r'^add/$',views.add_post,name='add'),

    # 个人页面
    url(r'^profile/(\d+)$', views.profile, name='profile'),
    url(r'^favorite/(\d+)$', views.favorite, name='favorite'),
    url(r'^like/(\d+)$', views.like, name='like'),
    url(r'^comment/(\d+)$', views.comment, name='comment'),
    url(r'^tranmite/(\d+)$', views.transmite, name='tranmite'),


    url(r'^update_ava/$',update.update_ava,name='update_ava'),
    url(r'^update_name/$',update.update_name,name='update_name'),
    url(r'^update_ph/$',update.update_ph,name='update_ph'),
    url(r'^update_maj/$',update.update_maj,name='update_maj'),
    url(r'^update_qq/$',update.update_qq,name='update_qq'),
    url(r'^update_signature/$',update.update_signature,name='update_signature'),


    url(r'^favorite/$', views.add_favorite, name='favorite'),
    url(r'^like/$', views.add_like, name='like'),
    url(r'^transmit/$', views.add_transmit, name='transmit'),

    url(r'^search/$', views.search, name='search'),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
]

posts/models.py
from django.db import models
from users.models import User
# Create your models here.
from DjangoUeditor.models import UEditorField
from django.urls import reverse
# class Articles(models.Model):


class Post(models.Model):
    POST_FROM = {
        0: u'原创',
        1: u'转载',
    }
    title = models.CharField(max_length=256, default='new blog',verbose_name='标题')
    # content_html = models.TextField(null=True, blank=True,verbose_name='内容')
    content_html = UEditorField(width=940, height=600, imagePath="images/",
                           filePath="images/", verbose_name=u"文章内容",blank=True,default='images/1.jpg')

    # 创建时间上和更新时间
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    modefied_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    # 定义外键关系
    author = models.ForeignKey(User, verbose_name='作者')
    category = models.ForeignKey('Category',blank=True ,verbose_name='话题')
    tags = models.ManyToManyField('Tag', blank=True,verbose_name='专栏')

    post_from = models.IntegerField(default=0, choices=POST_FROM.items(), verbose_name=u'文章来源')

    # 点赞，评论，收藏，转发数量
    like_num = models.IntegerField(default=0)
    comment_num = models.IntegerField(default=0)
    favo_num = models.IntegerField(default=0)
    transmit_num = models.IntegerField(default=0)

    # 精华帖子模型，精华区分类和是否是精华帖
    best = models.ForeignKey('Best',blank=True,verbose_name='精华',null=True,default=None)
    best_act = models.IntegerField(default=0)

    # 阅读数
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        #/post/1/
        return reverse('posts:detail',kwargs={'pk':self.pk})


    class Meta:
        verbose_name_plural = '帖子'
        verbose_name = '帖子'


class Best(models.Model):       # 是否是精华帖子
    name = models.CharField(max_length=256)

    def __str__(self):
        return  self.name


class Tag(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Like(models.Model):
    """点赞"""
    post = models.ForeignKey("Post")
    user = models.ForeignKey(User)
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    def __str__(self):
        return "%s likes post %s" % (self.user, self.post)


class Favorite(models.Model):
    """收藏"""
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    def __str__(self):
        return "%s collect post %s" % (self.user, self.post)

class Transmit(models.Model):
    """转发 """
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')

    def __str__(self):
        return "%s collect post %s" % (self.user, self.post)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

# user 包括 学号，姓名，专业，QQ


class User(AbstractUser):
    SEX_CHOICES = (
        ('男', 1),
        ('女', 0),)
    student_num = models.CharField(max_length=64,verbose_name="学号")
    qq_num = models.CharField(max_length=64,blank=True,verbose_name="qq号")
    major = models.CharField(max_length=64,blank=True,verbose_name="专业")
    sex = models.CharField(max_length=1,choices=SEX_CHOICES,verbose_name='性别',default=1)
    phone = models.CharField(max_length=20,blank=True,verbose_name='电话')
    avatar = models.ImageField(blank=True, upload_to='images/',default='images/1.jpg',verbose_name='头像')
    signature = models.CharField(max_length=128, default='This guy is too lazy to leave anything here!')
class Meta(AbstractUser.Meta):
        pass

posts/forms.py
from django import forms

from .models import Post,User



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [ 'title','content_html','category','tags']


class AvaForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['avatar']

class UsrForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

class SigForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['signature']

class QqForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['qq_num']

class MaForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['major']

class PhForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['phone']

posts/views.py
from django.shortcuts import render,get_object_or_404,render_to_response,HttpResponse
from posts.models import Post,Category,Like,Favorite,Tag,Transmit
from .forms import PostForm,AvaForm,UsrForm,PhForm,SigForm,QqForm,MaForm
from users.models import User
from comments.models import Comment
from comments.forms import CommentForm
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import datetime
import json
from comments.models import CommentReply
from hotinfo.models import HotInfo
from comments.views import new_comment

### 日期测试 文章按以下时间排序
today = datetime.date.today()
# print(today)
year = today.year
month = today.month
day = today.day
week = today.weekday()     #Day of week Monday = 0, Sunday = 6
# 本周是从周一开始 周天 按周查询逻辑: 如果今天是0 那么就是今天的日期.如果是6 那么就是今天日期,推6天

sartdata = datetime.date(year,month,day-week-2)
enddata = datetime.date(year,month,day+week)
# sartdata = datetime.date(2018,4,11)
# enddata = datetime.date(2018,4,16)
def index (request):
    # if request.method=='GET':
    #     return HttpResponse('welcome')
    return  render(request,'posts/index2.html',{})



class IndexView(ListView):          # 分页器写法
    global year,month,day,week,sartdata,enddata
    model = Post
    template_name = 'posts/index.html'
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 9


    # 重写get_context_data,一遍放入我们的分页的起始页面和结束页码
    def get_context_data(self, **kwargs):
        print('--------------11111111111')
        print(kwargs)
        print('2222222222222222222')
        # 调用父类的get_context_data方法
        context = super().get_context_data(**kwargs)
        hot_list = Post.objects.all().order_by('-views')[0:8]   # 热点信息
        hotinfo = HotInfo.objects.all()[0:10]
        timeweek = Post.objects.filter(created_time__range=(sartdata,enddata)).order_by('-views')
        timemonth = Post.objects.filter(created_time__month= month).order_by('-views')[0:8]
        timeday = Post.objects.filter(created_time__day= day).order_by('-views')



        # 最新评论逻辑：当前登录的作者，找到他所发布的所有帖子，再遍历每篇帖子，
        # 找到帖子下所有的评论，再截取最前面的评论，放到一个列表，再遍历列表，显示最前面的
        ########## 最新评论 #########
        #context.get()
        print(context)
        context.update({'hot_list': hot_list,'hotinfo':hotinfo,'timeweek':timeweek,'timemonth':timemonth,'timeday':timeday})
        return context


    '''
    
    def get (self,request,*args,**kwargs):
        print('-------------------------------22222222222')
        print(kwargs)
        userid = request.user

        newcomment_list = []
        post_list = Post.objects.filter(author_id=userid)
        for post in post_list:
            comm_list = post.comment_set.all()
            num = len(comm_list)
            print('-----------------------------------------------------num', num)
            if num == 0:
                pass
            else:
                newcomment_list.append(post)
        print('------------------------------------newcomment_list', newcomment_list)
        hot_list = Post.objects.all().order_by('-views')[0:8]  # 热点信息
        post_list = Post.objects.all()
        # context = ({'newcomment_list':newcomment_list})
        paginate_by = self.paginate_by
        context = super()
        return render(request,self.template_name,locals())
    '''





def posts(request):         # 原始写法
    post_list = Post.objects.all().order_by('-created_time')
    hot_list = Post.objects.all().order_by("-views")

    return render(request,'posts/index.html',locals())


def detail(request, pk):

    post = get_object_or_404(Post, pk=pk)
    reply_list = CommentReply.objects.all()
    hot_list = Post.objects.all().order_by('-views')[0:8]  # 热点信息
    ####评论的用户#####

    # 阅读量 +1
    post.increase_views()
    # 生成评论form表单
    form = CommentForm()
    # 把post的评论列表传到前台
    comment_list = post.comment_set.all().order_by('-created_time')
    avt = []
    # 根据评论和post_id 查找评论的user_id 再获取user的信息
    if len(comment_list) > 0:
        for commen in comment_list:
            com_id = commen.id
            q = {'id': com_id, 'post_id': pk}
            com_list = Comment.objects.filter(**q)   # 找到用户对象集

            if len(com_list) > 0:
                for com in com_list:
                    userid = com.user_id        # 找到用户id
                    print(userid)
                    userobj = User.objects.get(id =userid)  # 用户对象单个
                    print(userobj)
                    print(userobj.avatar)
                    avt.append(userobj)
    print(avt,type(avt))

    # post.content = markdown.markdown(post.content,
    #                     extensions=[
    #                         'markdown.extensions.extra',
    #                         'markdown.extensions.codehilite',
    #                         'markdown.extensions.toc'
    #                     ])
    # post.increase_views()
    return render(request, 'posts/detail3.html', locals())

def categories(request, pk):
    # 根据pk取得category对象db
    category = get_object_or_404(Category, pk=pk)
    # 根据取得category来正向查找post
    # post_list = Post.objects.filter(category=category)
    # 反向查
    post_list = category.post_set.all()
    return render(request, 'posts/index.html', locals())


def tags(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    # 反向查
    post_list = tag.post_set.all()
    return render(request, 'posts/index.html', {'post_list': post_list})

@login_required
def add_post(request):        # 发帖

    post_list = Post.objects.all().order_by('-created_time')
    hot_list = Post.objects.all().order_by("-views")[0:8]
    form = PostForm(instance=request.user)
    # 判断request的请求方法，如果是post方法，那么就处理数据
    if request.method == 'POST':
        # 获取前台传过来的数据，用来生成form对象
        form = PostForm(request.POST)

        # 判断form表单数据是否合法
        if form.is_valid():
            post = form.save(commit=False)
            # 如果合法，则保存数据
            post.author=request.user
            form.save()
            # print(form.cleaned_data)
            post_list = Post.objects.all().order_by('-created_time')
            return render(request,'posts/index.html', {'post_list': post_list})
            # return HttpResponse("{'status':'success'}", content_type='application/json')
            # messages.success(request, '保存成功！')
            # return HttpResponseRedirect('/index')
    return render(request, 'posts/add.html', locals())
    # 如果是get方法，就返回用户信息修改页面

@login_required
def profile(request,pk):    # 个人页面
    user = User.objects.get(pk=pk)
    post_list = user.post_set.all()
    return render(request, 'posts/profile.html',locals())


def like(request,pk):    # 个人页面
    user = User.objects.get(pk=pk)
    fav_list = user.like_set.all()
    return render(request, 'posts/profile.html',locals())


def favorite(request,pk):    # 个人页面
    user = User.objects.get(pk=pk)
    fav_list = user.favorite_set.all()

    return render(request, 'posts/profile.html',locals())


def transmite(request,pk):    # 个人页面
    user = User.objects.get(pk=pk)
    fav_list = user.transmit_set.all()

    return render(request, 'posts/profile.html',locals())

def comment(request,pk):    # 个人页面
    user = User.objects.get(pk=pk)
    fav_list = user.comment_set.all()
    return render(request, 'posts/profile.html',locals())

@login_required
def add_favorite(request):
    print('hello')
    if request.is_ajax():
        user = request.user
        contentid = request.POST.getlist('contend_id')

        # contentid = request.POST.get('contend_id')
        print(contentid[0])
        post = Post.objects.get(id=contentid[0])
        print(post)
        created_time = datetime.datetime.now()
        post_id = Favorite.objects.filter(post_id=post)
        print(post_id)
        if post_id.exists():
            resp = {'status': '已经收藏'}
            return HttpResponse(json.dumps(resp), content_type="application/json")

        else:
            post.favo_num +=1
            post.save()
            Favorite.objects.update_or_create(user=user, post=post, created_time=created_time)
            resp = {'errorcode': 100, 'status': '收藏成功'}
            return HttpResponse(json.dumps(resp), content_type="application/json")

@login_required
def add_like(request):
    if request.is_ajax():
        user = request.user
        contentid = request.POST.getlist('contend_id')

        # contentid = request.POST.get('contend_id')
        post = Post.objects.get(id=contentid[0])
        created_time = datetime.datetime.now()
        post_id = Like.objects.filter(post_id=post)
        if post_id.exists():
            resp = {'status': '已经点赞'}
            return HttpResponse(json.dumps(resp), content_type="application/json")
        else:
            post.like_num +=1
            post.save()
            Like.objects.update_or_create(user=user, post=post, created_time=created_time)
            resp = {'errorcode': 100, 'status': '成功点赞'}
            return HttpResponse(json.dumps(resp), content_type="application/json")

@login_required
def add_transmit(request):      # 转发
    path = request.path
    user = request.user
    post = Post.objects.all()

    if request.is_ajax():
        user = request.user
        contentid = request.POST.getlist('contend_id')

        # contentid = request.POST.get('contend_id')
        post = Post.objects.get(id=contentid[0])

        post.save()

        created_time = datetime.datetime.now()
        post_id = Transmit.objects.filter(post_id=post)
        if post_id.exists():
            resp = {'status': '已转发'}
            return HttpResponse(json.dumps(resp), content_type="application/json")
        else:
            post.transmit_num += 1
            post.save()
            post.id = None  # 只需要改变新对象的主键值，然后运行save() 复制数据库
            post.post_from += 1
            post.views = 0
            post.save()
            Transmit.objects.update_or_create(user=user, post=post, created_time=created_time)
            resp = {'errorcode': 100, 'status': '成功转发'}

posts/templates/posts/add.html
{#  <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">#}
{% extends "posts/base.html" %}
{#{% load staticfiles %}#}
{#{% load static %}#}

{#<title>添加数据，提交form表单</title>#}
{##}
{#{% block content %}#}
{#    <div class="col-sm-6">#}
{#    <h1>hello</h1>#}
{#    <div class="container">#}
{#        <form action="{% url 'posts:add' %}" method="post" role="form">#}
{#            {% csrf_token %}#}
{#                    {% for field in form %}#}
{#                        {{ field.label_tag }}#}
{#                        {{ field }}#}
{#                        {{ field.errors }}#}
{#                        {% if field.help_text %}#}
{#                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}
{##}
{#         <input type="submit" value="提交">#}
{##}
{#        </form>#}
{#    </div>#}
{##}
{#    </div>#}
{##}
{#{% endblock %}#}

{#{% extends "posts/base.html" %}#}
{% load static %}
{% load staticfiles %}
{% load bootstrap3 %}
{% load blog_tags %}
{#{% block title %} 湖北工业大学 BBS站{% endblock %}#}
{% block left %}
    		<!-- Left Column -->
		<div class="col-sm-3">
<!-- Text Panel -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3  style="color: red" class="panel-title">
						<span class="glyphicon glyphicon-bullhorn"></span>
						公告：新人必读
					</h3>
				</div>
				<div class="panel-body">
					<p style="color:red;">请文明浏览帖子，发布帖子，文明用语，禁止不良内容的发布，一经发现，封号三天，请注意</p>
                    <p style="color:red;">游客需要登录才能发帖，转贴，点赞和收藏</p>
					<div class="btn-group" role="group">
						<button type="button" class="btn btn-default">Resource</button>
						<button type="button" class="btn btn-default">Envision</button>
						<button type="button" class="btn btn-default">Niche</button>
					</div>
				</div>
			</div>


			<!-- List-Group Panel -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1 class="panel-title"><span class="glyphicon glyphicon-tags"></span> 话题 </h1>
				</div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title"></h3>
                    {% get_tags as tag_list %}
                    <ul class="fa-ul">
                        {% for tag in tag_list %}

                            <li class=" ">
                                <a style="font-size: medium" href="{% url 'posts:tags' tag.pk %}">{{ tag.name }}({{ tag.num_post }})</a>
                            </li>
                        {% empty %}
                            暂无标签
                        {% endfor %}
                    </ul>
                </div>
{#				<div class="list-group">#}
{#					<a href="#" class="list-group-item">Embrace Change </a>#}
{#					<a href="#" class="list-group-item">KISS: Keep it simple, stupid!</a>#}
{#					<a href="#" class="list-group-item">Hide Implementation Details</a>#}
{#					<a href="#" class="list-group-item">LoD: Law of Demeter</a>#}
{#					<a href="#" class="list-group-item">DRY: Don't Repeat Youself</a>#}
{#				</div>#}
			</div>

			<!-- Text Panel -->
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1 class="panel-title"><span class="glyphicon glyphicon-pencil"></span> 热点信息</h1>
				</div>

				<div class="panel-body">
                    <div class="row pre-scrollable">
                    <li class="list-group-item"><a href=" http://yz.chsi.com.cn">中国研究生招生信息网</a></li>

                    <li class="list-group-item"><a href=" http://dean.hbut.edu.cn">湖北工业大学教务处</a></li>
                    <li class="list-group-item"><a href="  http://jy.hbut.edu.cn">湖北工业 大学就业信息网</a></li>
                    <li class="list-group-item"><a href="  http://jy.hbut.edu.cn">湖北工业 大学就业信息网</a></li>
                    <li class="list-group-item"><a href="  http://jy.hbut.edu.cn">湖北工业 大学就业信息网</a></li>
                    <li class="list-group-item"><a href="  http://jy.hbut.edu.cn">湖北工业 大学就业信息网</a></li>
                        <li class="list-group-item"><a href="  http://jy.hbut.edu.cn">湖北工业 大学就业信息网</a></li>
                         <li class="list-group-item"><a href="  http://jy.hbut.edu.cn">湖北工业 大学就业信息网</a></li>
                         <li class="list-group-item"><a href="  http://jy.hbut.edu.cn">湖北工业 大学就业信息网</a></li>
                    </div>
					<p><button class="btn btn-default">Engage</button></p>
				</div>
			</div>



		</div><!--/Left Column-->
{% endblock %}
{% block conten %}
		<!-- Center Column -->
		<div class="col-sm-6">
			 <div class="container">
        <form action="{% url 'posts:add' %}" method="post" role="form">
            <div class="row" style="width: 940px;">
                {{ form.media }}
                {% bootstrap_form form %}

            </div>
            {% csrf_token %}
{#                    {% for field in form %}#}
{#                        {{ field.label_tag }}#}
{#                        {{ field }}#}
{#                        {{ field.errors }}#}
{#                        {% if field.help_text %}#}
{#                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}

         <input type="submit" value="提交">

        </form>
    </div>
			<hr>

			<div class="row">
				<article class="col-xs-12">
					<h2>Premier Niche Markets</h2>
					<p>Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive e-commerce via process-centric "outside the box" thinking. Completely pursue scalable customer service through sustainable potentialities.</p>
					<p><button class="btn btn-default">Read More</button></p>
					<p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">post</span></p>
					<ul class="list-inline">
						<li><a href="#">Today</a></li>
						<li><a href="#"><span class="glyphicon glyphicon-comment"></span> 2 Comments</a></li>
						<li><a href="#"><span class="glyphicon glyphicon-star-empty"></span> 8 favorites</a></li>
					</ul>
				</article>
			</div>
			<hr>
		</div><!--/Center Column-->


{% endblock %}

posts/templates/posts/index2.html
<!DOCTYPE html>
<html lang="zh-cn">
	<head>
        {% load static %}
{#        {% static "css/bootstrap.min.css" %}#}
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
		<link href="{% static "css/index.css" %}" rel="stylesheet" />
		<link href="{% static "css/common.css" %}" rel="stylesheet" />
		<!--
        	描述：网页的icon图标
        -->
		<link rel="shortcut icon" href="{% static "img/favicon.ico" %}"/>
		<title>欢迎进入湖北工业大学BBS站</title>
	</head>
	<body style=" padding-top: 15px;padding-bottom: 40px;">
		<div class="container-fluid" style="width: 70%;" >
			<img src="{% static "img/hbut1.jpg" %}" style="width: 100%;"/>
			<div style="height: 15px;"></div>
			<!--
            	描述：登录/注册/游客功能
            -->
			<center>
{#			<form class="form" action="{% url 'users:login' %}" method="post">#}
{#				账号:<input class="textinput" id="id_username" name="username" type="text" />#}
{#				密码:<input class="textinput" id="id_password" type="password" name="password"/>#}
{#				<label><input type="checkbox" id="auto" name="auto"/> 记住我</label>#}
                    <a href="{% url 'login' %}?next={{ request.path }}"><button type="button" class="btn btn-outline-primary btn-sm">登录</button></a>
				<a href="{% url 'users:register' %}"><button type="button" class="btn btn-outline-primary btn-sm">注册</button></a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'posts:index' %}" ><button type="button" class="btn btn-outline-primary btn-sm">Hi:{{ user.username }} 进入主页</button></a>
                {% else %}
                 <a href="{% url 'posts:index' %}" ><button type="button" class="btn btn-outline-primary btn-sm">游客</button></a>
                {% endif %}
{#			</form>#}
			<hr size="0" width="90%" color="#007BFF">
			</center>
		</div>
		<!--
        	描述：每页底部固定模板
        -->
		<div class="footer">
			<span> Copyright &copy; 2018 <a href="###">湖北工业大学 BBS站</a> &nbsp;湖北工业大学. All rights reserved.<br /></span>
			
		</div>
	</body>
</html>

posts/templates/posts/main.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="css/common.css" rel="stylesheet" />
		<!--
        	描述：网页的icon图标
        -->
		<link rel="shortcut icon" href="img/favicon.ico"/>
		<title>湖北工业大学 BBS站</title>
	</head>
	<body>
		
		<!--
        	描述：每页底部固定模板
        	-->
		<div class="footer">
			<span> Copyright &copy; 2018 <a href="###">湖北工业大学 BBS站</a> &nbsp;湖北工业大学. All rights reserved.<br /></span>
			
		</div>
	</body>
</html>

posts/templates/posts/prof_self.html
{% extends 'posts/profile.html' %}